import { useEffect, useMemo, useState } from 'react'
import { Dashboard } from './components/Dashboard'
import { ExpenseForm } from './components/ExpenseForm'
import { monthKey, yen } from './domain/calculations'
import type { AppSettings, Expense, ExpenseInput } from './domain/types'
import { IndexedDbExpenseRepository } from './repositories/IndexedDbExpenseRepository'
import { loadSettings, saveSettings } from './services/settings'

const repository = new IndexedDbExpenseRepository()
export default function App() {
  const [month, setMonth] = useState(monthKey(new Date())); const [expenses, setExpenses] = useState<Expense[]>([]); const [settings, setSettings] = useState<AppSettings>(loadSettings); const [editing, setEditing] = useState<Expense | null>(null); const [showSettings, setShowSettings] = useState(false); const [loading, setLoading] = useState(true)
  const monthLabel = useMemo(() => `${month.slice(0, 4)}年${Number(month.slice(5))}月`, [month])
  const refresh = async () => { setLoading(true); setExpenses(await repository.listByMonth(month)); setLoading(false) }
  useEffect(() => { void refresh() }, [month])
  const updateSettings = (next: AppSettings) => { setSettings(next); saveSettings(next) }
  const saveExpense = async (input: ExpenseInput, id?: string) => { await repository.save(input, id); setEditing(null); await refresh() }
  const remove = async (id: string) => { if (window.confirm('この支出を削除しますか？')) { await repository.remove(id); await refresh() } }
  const setBudget = (value: string) => { const amount = Number(value); if (Number.isInteger(amount) && amount >= 0) updateSettings({ ...settings, budgets: { ...settings.budgets, [month]: amount } }) }
  const addCategory = (name: string) => { const category = name.trim(); if (category && !settings.categories.includes(category)) updateSettings({ ...settings, categories: [...settings.categories, category] }) }
  return <main className="app-shell"><header><div><p className="eyebrow">CARD SPEND</p><h1>カード支出</h1></div><button className="icon-button" aria-label="設定" onClick={() => setShowSettings(x => !x)}>⚙</button></header><section className="month-switcher" aria-label="表示月"><button onClick={() => setMonth(prev => { const d = new Date(`${prev}-01T00:00:00`); d.setMonth(d.getMonth() - 1); return monthKey(d) })}>‹</button><strong>{monthLabel}</strong><button onClick={() => setMonth(prev => { const d = new Date(`${prev}-01T00:00:00`); d.setMonth(d.getMonth() + 1); return monthKey(d) })}>›</button></section>{showSettings && <section className="card settings"><div className="section-heading"><h2>設定</h2><button className="text-button" onClick={() => setShowSettings(false)}>閉じる</button></div><label>月間予算（{monthLabel}）<input aria-label="月間予算" type="number" min="0" inputMode="numeric" value={settings.budgets[month] ?? ''} onChange={e => setBudget(e.target.value)} placeholder="例：120000" /></label><div className="field-row"><label>注意（%）<input type="number" min="1" max="99" value={settings.warningThresholds.caution} onChange={e => updateSettings({ ...settings, warningThresholds: { ...settings.warningThresholds, caution: Number(e.target.value) } })} /></label><label>警告（%）<input type="number" min="1" max="99" value={settings.warningThresholds.warning} onChange={e => updateSettings({ ...settings, warningThresholds: { ...settings.warningThresholds, warning: Number(e.target.value) } })} /></label></div><form onSubmit={e => { e.preventDefault(); addCategory(new FormData(e.currentTarget).get('category') as string); e.currentTarget.reset() }}><label>カテゴリを追加<input name="category" maxLength={30} placeholder="例：医療費" /></label><button className="secondary-button">追加</button></form></section>}<Dashboard expenses={expenses} settings={settings} month={month} /><ExpenseForm categories={settings.categories} editing={editing} onSave={saveExpense} onCancel={() => setEditing(null)} /><section className="card history"><div className="section-heading"><h2>支出履歴</h2><span>{expenses.length} 件</span></div>{loading ? <p className="empty">読み込み中…</p> : expenses.length ? <ul>{expenses.map(item => <li key={item.id}><div><span>{item.date} ・ {item.category}</span><b>{yen(item.amount)}</b>{item.memo && <small>{item.memo}</small>}</div><div className="item-actions"><button onClick={() => setEditing(item)}>編集</button><button className="delete" onClick={() => void remove(item.id)}>削除</button></div></li>)}</ul> : <p className="empty">この月の支出はありません。</p>}</section><footer>データはこのブラウザ内にだけ保存されます。</footer></main>
}
